---
title: "Formal problem Statement"
author: "Murugesan Nagarjan"
date: "April 17, 2018"
output: html_document
---


## Introduction

Bank ABC's marketing department markets Bank products like Checking account, saving account, term deposit and Loan products to their customers. As part of this marketing calls, the marketing team contact various people and gather initial information about the customer and store them in a call history database. The database has the past call history and details about how many such a call turned into potential buyer.

The team has around 2 years' worth of call history and the outcome details whether a customer turned into buyer or not. The department director complained that the team is spending lot of effort on making this phone call campaign, but very little prospect become clients for them. He wanted improve the no of sales target.


## Purpose

The purpose of this project is to reduce the marketing campaign spending cost and increase the sales target (sales per call)


## Stake holders

Project sponsor: Marketing department director.
End Users: Marketing team.
Project Manager: IT project Manager
Project Team: Data scientist, Data Engineer and Business Analyst
Business user:  Marketing Lead

## Success criteria

Predicting whether a customer call become a client or not and reducing the no of calls to customer that will not turn into client.

## Risk

Chances of losing potential client due to unavailability of data in call history.

## Project usage

Marketing team should provide the customer attributes (feature) to the developed Machine Learning model and predict whether this customer will subscribe to a bank product.


## Project timeline:
Project Phase|efforts
-------------|-------
Data collection|20 days
Organize and Store |20 days
Utilize and build model | 40 days 
Test and validate the Mode | 10 days
Decide |  10 days
